name: Deploy Next.js to VPS

on:
  workflow_dispatch: {}   # run it manually from the Actions tab
  push:
    branches: [ "master" ]  # optional: run on push too

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS and rebuild
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            set -e
            # Navigate to project directory
            cd /projects/laxzin/laxzin-frontend
            
            # Get latest code from repository
            git fetch origin master
            git reset --hard origin/master
            
            # Install dependencies and build
            npm install
            npm run build
            
            # Restart PM2 process
            pm2 stop laxzin-frontend || true
            pm2 start npm --name "laxzin-frontend" -- start
            
            # Verify deployment
            echo "Deployment completed at $(date -u)"
            pm2 list
