name: Connect VPS (smoke test)

on:
  workflow_dispatch: {}   # run it manually from the Actions tab
  push:
    branches: [ "master" ]  # optional: run on push too

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (not strictly needed here)
        uses: actions/checkout@v4

      - name: Ensure target dir exists & write marker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            set -e
            mkdir -p /projects/laxzin/laxzin-frontend
            cd /projects/laxzin/laxzin-frontend
            echo "CI connected at $(date -u)" > CI_CONNECTED.txt
            echo "whoami: $(whoami)"
            echo "pwd: $(pwd)"
            ls -la
