name: Deploy to VPS (password)

on:
  push:
    branches: [ "master" ]   # change if you deploy a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # Upload only what you need to run (adjust paths as needed)
      - name: Upload app to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          source: |
            .next/**
            package.json
            package-lock.json
            next.config.js
            public/**
            .env.local
          target: /root/projects/laxzin/laxzin-frontend
          strip_components: 0
          overwrite: true

      - name: Install production deps & restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            cd /root/projects/laxzin/laxzin-frontend
            # ensure pm2 is available
            if ! command -v pm2 >/dev/null 2>&1; then npm i -g pm2; fi
            # install only prod deps (nothing to build on server, we uploaded .next)
            npm ci --omit=dev
            # start or restart
            if pm2 status laxzin-frontend >/dev/null 2>&1; then
              pm2 restart laxzin-frontend
            else
              pm2 start npm --name "laxzin-frontend" -- start
              pm2 save
            fi
