name: Deploy to VPS (password)

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Debug so we can see the files that will be uploaded
      - name: List built files
        run: |
          pwd
          ls -la
          ls -la laxzin-frontend || true
          ls -la laxzin-frontend/.next || true

      - name: Ensure target dir exists on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          script: mkdir -p /projects/laxzin/laxzin-frontend

      # IMPORTANT: prefix sources with the subfolder
      - name: Upload app to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          source: |
            laxzin-frontend/.next/**
            laxzin-frontend/package.json
            laxzin-frontend/package-lock.json
            laxzin-frontend/next.config.js
            laxzin-frontend/public/**
          target: /projects/laxzin/laxzin-frontend
          overwrite: true

      - name: Install production deps & restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            cd /projects/laxzin/laxzin-frontend
            if ! command -v pm2 >/dev/null 2>&1; then npm i -g pm2; fi
            npm ci --omit=dev
            if pm2 status laxzin-frontend >/dev/null 2>&1; then
              pm2 restart laxzin-frontend
            else
              pm2 start npm --name "laxzin-frontend" -- start
              pm2 save
            fi
